/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fhi.kidmap.business;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * @author smomoh
 */
public class ProcessMonitor implements Serializable
{
    private String processId;
    private String processName;
    private int processStatus;
    private int autogenerated;
    private int repeatAction;
    private Date lastModifiedDate;

    public int getAutogenerated() {
        return autogenerated;
    }

    public void setAutogenerated(int autogenerated) {
        this.autogenerated = autogenerated;
    }

    public Date getLastModifiedDate() {
        return lastModifiedDate;
    }

    public void setLastModifiedDate(Date lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    public String getProcessId() {
        return processId;
    }

    public void setProcessId(String processId) {
        this.processId = processId;
    }

    public String getProcessName() {
        return processName;
    }

    public void setProcessName(String processName) {
        this.processName = processName;
    }

    public int getProcessStatus() {
        return processStatus;
    }

    public void setProcessStatus(int processStatus) {
        this.processStatus = processStatus;
    }

    public int getRepeatAction() {
        return repeatAction;
    }

    public void setRepeatAction(int repeatAction) {
        this.repeatAction = repeatAction;
    }
    
}
